spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: lumitechcity@gmail.com
    password: tsvx lsuo arkz fbke
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/oasis_xchanger?useSSL=false&serverTimezone=UTC  # Ensure SSL is configured properly
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8 dialect
    show-sql: true

server:
  port: 9092

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.authentication: trace
    org.springframework.security.authorization: debug
